services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - weather-app-network
    environment:
      - SUPABASE_URL=https://maxbgsangddavxdfuqlo.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1heGJnc2FuZ2RkYXZ4ZGZ1cWxvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODQ3MzkyNCwiZXhwIjoyMDY0MDQ5OTI0fQ.W1lFDs0xYCchhlsDAfNgB2PvKkpP8_stwX7pa14c3GY



  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    restart: always
    networks:
      - weather-app-network


networks:
  weather-app-network:
    driver: bridge
