
---
- name: Server vorbereiten
  hosts: appserver
  become: yes

  tasks:
    - name: System aktualisieren
      apt:
        update_cache: yes
        upgrade: dist

    - name: Docker installieren
      apt:
        name: [docker.io, docker-compose]
        state: present

    - name: Docker-Dienst starten
      service:
        name: docker
        state: started
        enabled: true